// Ela AI Assistant Types for Berjaya WMS

// Message interface - individual chat messages
export interface ElaMessage {
  id: string;
  conversationId: string;
  role: 'user' | 'ela';
  content: string;
  timestamp: Date;
}

// Conversation interface - conversation metadata
export interface ElaConversation {
  id: string;
  userId: string;
  userEmail: string;
  userRole: string;
  userName: string;
  startTime: Date;
  lastMessageTime: Date;
  messageCount: number;
  status: 'active' | 'closed';
  summary?: string; // Generated by AI after conversation
}

// Message data for API calls (without ID and timestamp)
export interface ElaMessageData {
  role: 'user' | 'ela';
  content: string;
}

// Conversation summary for manager dashboard
export interface ElaConversationSummary {
  conversation: ElaConversation;
  lastMessage: string;
  timeAgo: string;
}

// Overall summary data for all conversations
export interface ElaOverallSummary {
  period: string; // "Last 7 days", "This month", etc.
  totalConversations: number;
  topIssues: string[];
  overallSentiment: 'positive' | 'neutral' | 'frustrated';
  summary: string; // Generated by AI
  generatedAt: Date;
}

// Props for Ela components
export interface ElaChatProps {
  user: {
    uid: string;
    email: string;
    displayName: string | null;
  };
  userRole: string;
  onClose: () => void;
}

export interface ElaMenuProps {
  onChatOpen: () => void;
  onPersonalSettingsOpen: () => void;
  onClose: () => void;
}